interface=""
internet_interface=""
phy_interface=""
bssid=""
essid=""
channel=""
et_dos_attack=""


ettercap_log=1
ettercap_logpath="/tmp/et_sniffing_captured.txt"
dos_pursuit_mode=0
mac_spoofing_desired=0
country_code="00"
standard_80211n=0
standard_80211ac=0
standard_80211ax=0
standard_80211be=0